name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
      
      - name: Build TypeScript
        run: npm run build
        
      # Add these new steps
      - name: Create .nojekyll
        run: touch build/.nojekyll
        
      - name: Create _config.yml
        run: |
          echo "include:" > build/_config.yml
          echo "  - '*.js'" >> build/_config.yml
        
      - name: List dist contents
        run: |
          echo "Root build directory:"
          ls -la build/
          echo "Data directory:"
          ls -la build/data/
      
      - name: Verify data.bin
        run: |
          if [ ! -f build/data/data.bin ]; then
            echo "Error: data.bin is missing!"
            exit 1
          fi
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4